platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'

target 'NativoSwiftTableViewSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK'

end
