platform :ios, '12.0'

source 'https://cdn.cocoapods.org/'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'

target 'Nativo-AppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionDemo
  pod 'NativoSDK', :path => '~/Documents/Nativo/NativoSDK-iOS-Workspace/NativoSDK-iOS'

end
