platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'

target 'CollectionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionDemo
  pod 'NativoSDK', '~> 6.0.0'

end
