platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'

target 'NativoGAMIntegrationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', '~> 6.0.0-alpha.1'
  pod 'Google-Mobile-Ads-SDK'

end
