# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NativoGAMIntegrationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', :path => '~/Documents/Nativo/NativoSDK-iOS-Workspace/NativoSDK-iOS'
  pod 'Google-Mobile-Ads-SDK'

end
