platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'

target 'NativoGAMIntegrationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', '~> 6.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 8.8.0'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.13.0'

end
